apiVersion : apps/v1
kind: Deployment
metadata:
  name: "yopasscluster-ee46"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "yopasscluster-ee46"
  template:
    metadata:
      labels:
        app: "yopasscluster-ee46"
    spec:
      containers:
        - name: "yopasscluster-ee46"
          image: "yopass.azurecr.io/yopasscluster"
          ports:
          - containerPort: 80